# Generated by Django 3.1.5 on 2021-06-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=256)),
                ('quote_len', models.IntegerField()),
            ],
        ),
    ]
